### ISSUE TITLE
Use SHA-384 for signature authentication

### ISSUE THREAD

**Issue by aduh95** [transloadit/rails-sdk#70]
Transloadit supports SHA-384 signatures, that what we should use considering SHA-1 vulnerabilities.

https://github.com/transloadit/rails-sdk/blob/4283e5d1ae335e79723c39d9a4a3a9d2af00d03c/lib/transloadit/rails/engine.rb#L86

**Comment by rmehner** [comment]
Hi,

thanks for the report. The algorithm is set in the [ruby-sdk](https://github.com/transloadit/ruby-sdk) right here: https://github.com/transloadit/ruby-sdk/blob/e9ca544c67447ef3e8727d721d92938a3cb86add/lib/transloadit/request.rb#L19

And since SHA-384 is supported in all supported ruby versions, we can change it there. Would you be willing to send a PR for that? And does this have any breaking changes then?

**Comment by Acconut** [comment]
I just merged the necessary changes in the Ruby SDK and prepared a new release: https://github.com/transloadit/ruby-sdk/releases/tag/v3.0.2

@rmehner Would you be able to push the release to RubyGems?

**Comment by rmehner** [comment]
Done: https://rubygems.org/gems/transloadit/versions/3.0.2

**Comment by Acconut** [comment]
Thank you!
